version: '3'
services:
  app:
    build: .
    restart: always
    container_name: hackerrank_challenge
    ports:
      - "8133:8133"
    networks:
      - web
    labels:
      - "traefik.enable=true"
      - "traefik.backend=hackerrank_challenge"
      - "traefik.frontend.rule=Host:hc.phamdung.me"
      - "traefik.port=8133"
    volumes:
      - ".:/app/"

networks:
  web:
    external: true